### ISSUE TITLE
UIHH Extraction

### ISSUE THREAD

**Issue by piggz** [SashaCX75/AmazFit_Watchface_Editor_2#3]
Apologies for raising this as an issue, I just wanted to contact you to understand if you had a parser for files with the header UIHH.

This format is not only used for watchfaces, but also the AGPS data, and it would be useful for GadgetBridge and Amazfish if we understood this format.

**Comment by SashaCX75** [comment]
To disassemble the dial and use this parser
https://github.com/Tnxec2/py_amazfit_tools/tree/GTS2
I have no other
