### ISSUE TITLE
GTS 2 : apparently newly supported json features (not yet supported in watchface editor)

### ISSUE THREAD

**Issue by gregory-dpt** [SashaCX75/AmazFit_Watchface_Editor_2#5]
Hi
My daughter (10 years old) has an amazfit GTS 2. And w have created some nice animated wtachfaces before using this watchface editor before (v1.2 at the time...).  (very nice work btw on the editor).

So now, we wanted to create a new watchface based on a personal background but combining the some of the features of official amazfit gts 2 face : "colorful numbers" (this editor is a nice/motivating way to teach my daughter some IT skills:).
But this "colorful numbers" watchface json seems to have quite a different syntax than the currently supported json features (when cross-checking inside code (https://github.com/SashaCX75/AmazFit_Watchface_Editor_2/tree/master/GTR_Watch_face)).

So it would be nice to also support in the code these new amazfit json features (a.o. time.hours.tens & time.hours.ones).
FYI: the problematic json code (note that I already modified it slightly to get it a bit more digestable by the amazfit watchface editor) (maybe also a good idea to look at the orginal/even_more_problematic json code): 
"
 "Info": {
    "DeviceId": 65
  },
  "Background": {
    "Image": {
      "X": 0,
      "Y": 0,
      "ImageIndex": 75
    },
    "Preview": [
	{
	  "LangCode": "All",
        "ImageSet": {
      "ImageIndex": 74,
	  "ImagesCount": 1
      }
	}
	]
  },
  "Time": {
    "Hours": {
      "Tens": {
        "X": 32,
        "Y": 40,
        "ImageIndex": 1,
        "ImagesCount": 3
      },
      "Ones": {
        "X": 182,
        "Y": 40,
        "ImageIndex": 3,
        "ImagesCount": 10
      }
    },
    "Minutes": {
      "Tens": {
        "X": 32,
        "Y": 260,
        "ImageIndex": 13,
        "ImagesCount": 10
      },
      "Ones": {
        "X": 182,
        "Y": 260,
        "ImageIndex": 23,
        "ImagesCount": 10
      }
    }
  },
  "Activity": {
    "Pulse": {
      "TopLeftX": 29,
      "TopLeftY": 212,
      "BottomRightX": 80,
      "BottomRightY": 213,
      "Alignment": "BottomLeft",
      "Spacing": 0,
      "ImageIndex": 62,
      "ImagesCount": 10
    },
    "NoDataImageIndex": 72
  },
  "Date": {
    "MonthAndDay": {
      "Separate": {
        "MonthName": {
          "X": 122,
          "Y": 208,
          "ImageIndex": 33,
          "ImagesCount": 12
        },
        "Day": {
          "TopLeftX": 89,
          "TopLeftY": 212,
          "BottomRightX": 123,
          "BottomRightY": 213,
          "Alignment": "BottomLeft",
          "Spacing": 0,
          "ImageIndex": 45,
          "ImagesCount": 10
        }
      },
      "TwoDigitsMonth": true,
      "TwoDigitsDay": true
    },
    "WeekDay": {
      "X": 188,
      "Y": 208,
      "ImageIndex": 55,
      "ImagesCount": 7
    }
  },
  "StepsProgress": {
    "Unknown5": {
      "CenterX": 0,
      "CenterY": 0,
      "RadiusX": null,
      "RadiusY": null
    }
  },
  "Battery": {
    "Text": {
      "TopLeftX": 275,
      "TopLeftY": 212,
      "BottomRightX": 326,
      "BottomRightY": 213,
      "Alignment": "Bottom",
      "Spacing": 0,
      "ImageIndex": 62,
      "ImagesCount": 10
    },
    "Unknown4": {
      "OnlyBorder": false,
      "Color": "0x0000000000000000",
      "CenterOffset": {
        "X": 0,
        "Y": 0
      },
      "Shape": {
        "X": 0,
        "Y": 0
      }
    },
    "PercentImage": {
      "X": 326,
      "Y": 212,
      "ImageIndex": 73
    }
  }
}
"

Regards
Gregory
(note that if needed I could join this DEV team to also contribute ... at the moment I just have a lot of github things i'm already contributing to...)

**Comment by kyle208** [comment]
You can submit your code. We'll welcome you to do so.

**Comment by SashaCX75** [comment]
@gregory-dpt 
Your code from the first generation watches (GTR / GTS). On the second generation watches (GTR 2, GTS 2 and others), the structure of the dials has changed. They added new features, but at the same time, several features disappeared. It does not depend on me, but on the manufacturer's company.

It is possible to convert watch faces from GTR to GTR 2 (the converter can be [found here](https://amazfitwatchfaces.com/forum/viewtopic.php?f=29&t=1888&start=275)). But on such dials, some functions may not work.

**Comment by gregory-dpt** [comment]
so It seems (since latest updates : the relase notes were saying support for extra widgets), that now GTS 2 accepts json files in GTS 1 json format (? maybe also a hybrid between them?) (but packed in GTS 2 format). 
The GTR 2 unpacker, successfully unpacks the files.
But the GTS 2 packer fails to pack them again. (and when using the GTR (1) watchface editor to pack --> not accepted by GTS 2)

**Comment by SashaCX75** [comment]
@gregory-dpt 
GTS 2 can use GTS 1 files, but this requires changing the bin header and using a different compression method. You can't make a hybrid watch face.

GTS 2 and GTR 2 files are interchangeable. Therefore, I don’t understand you when you talk about different unpackers for GTS 2 and GTR 2. There is only one unpacker for them. If the unpacker can unpack the file, then it can pack it back.

**Comment by gregory-dpt** [comment]
Hi
Thanks for the reply (really useful).
So indeed, GTS2 can use GTS 1 files (sorry I did not know that before).
I  have managed to repack & change the header & successfully have the gts 2 watch accept the GTS 1 format  face.  (thanks)
What I did: I used py-amazfit-tools-GTS2 branch (https://github.com/Tnxec2/py_amazfit_tools/tree/GTS2).
there is an option oldformat (?probably also present in main github py_amazfit_tools branch?) :  python ./main.py --gts2 --oldformat --file .\d9d5990fXXX.json

Maybe it's useful to also support such an option ("--oldformat") in SashaCX75 / AmazFit_Watchface_Editor_2 ?
...as said earlier, I could help with introducing that option (if not already supported somehow)...

Wrt GTS2 & GTR 2 files : they are indeed interchangeable (just a typo) (the problem is that the default "packing/compiling" of GTS 1 json into a GTS 2 bin file (packed/unpacked) does not work (e.g. due to the maybe missing  option "-- oldformat") .

**Comment by SashaCX75** [comment]
This editor does not support using GTS1 watch faces for GTS2. Such dials have a very different structure and different capabilities, so I see no reason to combine these dials in one editor.

If you want to use GTS1 watch faces for GTS2 you can use "[GTR (GTS, T-Rex) to GTR2 (GTS 2, T-Rex Pro) Converter & Editor](https://amazfitwatchfaces.com/forum/viewtopic.php?p=8844#p8844)". But such dials do not always work correctly, so I do not plan to further develop this direction.
