### ISSUE TITLE
T-rex PRO - PAI 

### ISSUE THREAD

**Issue by MiraVorlik** [SashaCX75/AmazFit_Watchface_Editor_2#8]
Hello, I am using T-Rex watch face editor by SashaCX75, version 11.1. Is it possible to display the PAI value as well? Thanks for the reply, or the download link.

**Comment by SashaCX75** [comment]
@MiraVorlik 
T-rex PRO uses AmazFit WatchFace editor 2, latest version 7.3. It has PAI.

**Comment by MiraVorlik** [comment]
Thank you very much, yes this version already has it.
